### PR TITLE
Be compat with ember 4

### PR DESCRIPTION
**Pull request by NullVoxPopuli**

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
Updated!

**Comment by NullVoxPopuli** [comment]
Node 10 might need to be dropped

**Comment by NullVoxPopuli** [comment]
whoops, I did this on the other PR

**Comment by NullVoxPopuli** [comment]
bah, why's it work locally. one sec

**Comment by NullVoxPopuli** [comment]
beta + canary will fail until https://github.com/ember-cli/ember-page-title/pull/218 is merged

**Comment by knownasilya** [comment]
Hum, seems like it needs a fastboot update? https://github.com/ember-cli/ember-page-title/pull/218/checks?check_run_id=3852118020#step:5:172

**Pull request closed without merging**
