### PR TITLE
feat: provide getPageTitle test helper to consuming apps

### PR DESCRIPTION
**Pull request by srsgores**
This PR allows consuming apps to assert a page's `title` (whether integration or acceptance test).

Usage documented in the `README.md`:

```javascript
import { getPageTitle } from 'ember-page-title/test-support';

module('Acceptance | Register Page', function(hooks) {
  setupApplicationTest(hooks);

  test('visiting /register', async function(assert) {
    const registerURL = '/register';
    await visit(registerURL);

    assert.equal(currentURL(), registerURL);
    assert.equal(getPageTitle(), 'Register | Some Website');
  });
});
```

### CODE REVIEW

**Review by knownasilya — CHANGES_REQUESTED** [review]
Some doc updates, otherwise looks good.

**Review by srsgores — COMMENTED** [review]
Should be updated

**Comment by knownasilya** [comment]
@raido thoughts on this addition? Since the helper was internal only before.

**Review by knownasilya — APPROVED** [review]

**Comment by srsgores** [comment]
I'll clarify that part of our enterprise front-end is waiting on this PR to get merged.  We had previously run our acceptance tests via a private helper as well, but this quickly became cumbersome when we needed to assert page titles on addon acceptance tests.

**Comment by srsgores** [comment]
@knownasilya, can we also bump `package.json` and release on npm?

**Comment by knownasilya** [comment]
Done

**Comment by raido** [comment]
I am a bit late here, but since this "private" helper is re-exported via index.js, it's fine. We can easily re-work internals.

We probably should add comment block so IDEs could give hints of expected parameters OR provide TypeScript interface file. I think proper JSDoc for starters would be nice.

This helper does have some internal logic comments in it, we should probably remove it or separate it still for testing specifically this addon vs public helper.

The `Array.pop()` workaround for consumers is not needed, it's only applicable for tests in this repository.

**Pull request merged**
