### PR TITLE
feat: Add glint types

### PR DESCRIPTION
**Pull request by muziejus**

### CODE REVIEW

**Review by chriskrycho — CHANGES_REQUESTED** [review]
Thanks for opening this—we should get *a* version of this landed. However, since this is one of the addons provided by Ember itself, per emberjs/rfcs#800, it's preferable here to simply convert it to TypeScript and ship types "natively" instead!

**Comment by muziejus** [comment]
Thanks, @chriskrycho… Is… converting to typescript… on the table? I could give that a try with this addon, which seems pretty compact. Or do these sorts of things have to wait for something else to happen?

**Comment by chriskrycho** [comment]
It’s entirely on the table: that was the whole point of the RFCs! 😁

**Comment by muziejus** [comment]
yay new project. Thanks, @chriskrycho !

**Pull request closed without merging**
