### PR TITLE
Fix release, beta and canary scenarios

### PR DESCRIPTION
**Pull request by bertdeblock**

### CODE REVIEW

**Review by mansona — APPROVED** [review]
Looks good 🎉

**Review by NullVoxPopuli — APPROVED** [review]

**Comment by bertdeblock** [comment]
@knownasilya Don't think these changes should be labelled as breaking.

**Comment by knownasilya** [comment]
You did update the node version and some of the import paths, I think those are breaking. I might be wrong..

**Comment by bertdeblock** [comment]
I only updated the pinned Node version using Volta to make CI happy (I did not update `engines`).
The other changes were only for the docs and test-app apps.

**Comment by NullVoxPopuli** [comment]
si, this is a browser-only v2 addon, so node version has no impact on consumers.

**Pull request merged**
