### PR TITLE
chore: Update URLs to match ember-cli organization

### PR DESCRIPTION
**Pull request by raido**
This PR updates all URLs to point to `ember-cli` organization instead of `adopted-ember-addons`.

We need to update also URL in repository settings, the one for About section on main page.

### CODE REVIEW

**Comment by knownasilya** [comment]
Thanks!

**Comment by knownasilya** [comment]
Cc @locks can you update the URL on the repo?

**Comment by locks** [comment]
Done!

**Comment by raido** [comment]
Thank you!

**Pull request merged**
